/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        stone: {
          950: '#0c0a09',
        },
        background: 'rgb(var(--color-background) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--color-surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--color-surface-3) / <alpha-value>)',
        'surface-4': 'rgb(var(--color-surface-4) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        'border-strong': 'rgb(var(--color-border-strong) / <alpha-value>)',
        'border-stronger': 'rgb(var(--color-border-stronger) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        'foreground-strong': 'rgb(var(--color-foreground-strong) / <alpha-value>)',
        'foreground-muted': 'rgb(var(--color-foreground-muted) / <alpha-value>)',
        'foreground-subtle': 'rgb(var(--color-foreground-subtle) / <alpha-value>)',
        'foreground-faint': 'rgb(var(--color-foreground-faint) / <alpha-value>)',
        'foreground-disabled': 'rgb(var(--color-foreground-disabled) / <alpha-value>)',
        'foreground-dim': 'rgb(var(--color-foreground-dim) / <alpha-value>)',
        backdrop: 'rgb(var(--color-backdrop) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-strong': 'rgb(var(--color-primary-strong) / <alpha-value>)',
        'primary-hover': 'rgb(var(--color-primary-hover) / <alpha-value>)',
        'primary-foreground': 'rgb(var(--color-primary-foreground) / <alpha-value>)',
        'primary-muted': 'rgb(var(--color-primary-muted) / <alpha-value>)',
        'primary-muted-foreground': 'rgb(var(--color-primary-muted-foreground) / <alpha-value>)',
        'info-muted': 'rgb(var(--color-info-muted) / <alpha-value>)',
        'info-muted-foreground': 'rgb(var(--color-info-muted-foreground) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
        'info-hover': 'rgb(var(--color-info-hover) / <alpha-value>)',
        'info-foreground': 'rgb(var(--color-info-foreground) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        'success-soft': 'rgb(var(--color-success-soft) / <alpha-value>)',
        'success-muted': 'rgb(var(--color-success-muted) / <alpha-value>)',
        'success-muted-foreground': 'rgb(var(--color-success-muted-foreground) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-strong': 'rgb(var(--color-warning-strong) / <alpha-value>)',
        'warning-soft': 'rgb(var(--color-warning-soft) / <alpha-value>)',
        'medal-bronze': 'rgb(var(--color-medal-bronze) / <alpha-value>)',
        'medal-bronze-soft': 'rgb(var(--color-medal-bronze-soft) / <alpha-value>)',
        'medal-bronze-foreground': 'rgb(var(--color-medal-bronze-foreground) / <alpha-value>)',
        'medal-silver': 'rgb(var(--color-medal-silver) / <alpha-value>)',
        'medal-silver-soft': 'rgb(var(--color-medal-silver-soft) / <alpha-value>)',
        'medal-silver-foreground': 'rgb(var(--color-medal-silver-foreground) / <alpha-value>)',
        'medal-gold': 'rgb(var(--color-medal-gold) / <alpha-value>)',
        'medal-gold-soft': 'rgb(var(--color-medal-gold-soft) / <alpha-value>)',
        'medal-gold-foreground': 'rgb(var(--color-medal-gold-foreground) / <alpha-value>)',
        danger: 'rgb(var(--color-danger) / <alpha-value>)',
        'danger-strong': 'rgb(var(--color-danger-strong) / <alpha-value>)',
        'danger-muted-foreground': 'rgb(var(--color-danger-muted-foreground) / <alpha-value>)',
        cta: 'rgb(var(--color-cta) / <alpha-value>)',
        'cta-foreground': 'rgb(var(--color-cta-foreground) / <alpha-value>)',
        'track-red': 'rgb(var(--color-track-red) / <alpha-value>)',
        'track-blue': 'rgb(var(--color-track-blue) / <alpha-value>)',
        'track-green': 'rgb(var(--color-track-green) / <alpha-value>)',
        'track-foreground': 'rgb(var(--color-track-foreground) / <alpha-value>)',
        logo: 'rgb(var(--color-logo) / <alpha-value>)',
        chip: 'rgb(var(--color-chip) / <alpha-value>)',
        'chip-foreground': 'rgb(var(--color-chip-foreground) / <alpha-value>)',
        'chip-border': 'rgb(var(--color-chip-border) / <alpha-value>)',
        caret: 'rgb(var(--color-caret-block) / <alpha-value>)',
        'caret-foreground': 'rgb(var(--color-caret-foreground) / <alpha-value>)',
        'caret-bar': 'rgb(var(--color-caret-bar) / <alpha-value>)',
        syntax: {
          keyword: 'rgb(var(--color-syntax-keyword) / <alpha-value>)',
          string: 'rgb(var(--color-syntax-string) / <alpha-value>)',
          comment: 'rgb(var(--color-syntax-comment) / <alpha-value>)',
          number: 'rgb(var(--color-syntax-number) / <alpha-value>)',
          operator: 'rgb(var(--color-syntax-operator) / <alpha-value>)',
          punctuation: 'rgb(var(--color-syntax-punctuation) / <alpha-value>)',
          function: 'rgb(var(--color-syntax-function) / <alpha-value>)',
          type: 'rgb(var(--color-syntax-type) / <alpha-value>)',
          preprocessor: 'rgb(var(--color-syntax-preprocessor) / <alpha-value>)',
          plain: 'rgb(var(--color-syntax-plain) / <alpha-value>)',
        },
        'key-orange': 'rgb(var(--color-key-orange) / <alpha-value>)',
        'key-orange-foreground': 'rgb(var(--color-key-orange-foreground) / <alpha-value>)',
        'key-orange-border': 'rgb(var(--color-key-orange-border) / <alpha-value>)',
        'key-blue': 'rgb(var(--color-key-blue) / <alpha-value>)',
        'key-blue-foreground': 'rgb(var(--color-key-blue-foreground) / <alpha-value>)',
        'key-blue-border': 'rgb(var(--color-key-blue-border) / <alpha-value>)',
        'key-cyan': 'rgb(var(--color-key-cyan) / <alpha-value>)',
        'key-cyan-foreground': 'rgb(var(--color-key-cyan-foreground) / <alpha-value>)',
        'key-cyan-border': 'rgb(var(--color-key-cyan-border) / <alpha-value>)',
        'key-purple': 'rgb(var(--color-key-purple) / <alpha-value>)',
        'key-purple-foreground': 'rgb(var(--color-key-purple-foreground) / <alpha-value>)',
        'key-purple-border': 'rgb(var(--color-key-purple-border) / <alpha-value>)',
        'key-green': 'rgb(var(--color-key-green) / <alpha-value>)',
        'key-green-foreground': 'rgb(var(--color-key-green-foreground) / <alpha-value>)',
        'key-green-border': 'rgb(var(--color-key-green-border) / <alpha-value>)',
        'key-red': 'rgb(var(--color-key-red) / <alpha-value>)',
        'key-red-foreground': 'rgb(var(--color-key-red-foreground) / <alpha-value>)',
        'key-red-border': 'rgb(var(--color-key-red-border) / <alpha-value>)',
        'key-yellow': 'rgb(var(--color-key-yellow) / <alpha-value>)',
        'key-yellow-foreground': 'rgb(var(--color-key-yellow-foreground) / <alpha-value>)',
        'key-yellow-border': 'rgb(var(--color-key-yellow-border) / <alpha-value>)',
        'key-neutral': 'rgb(var(--color-key-neutral) / <alpha-value>)',
        'key-neutral-foreground': 'rgb(var(--color-key-neutral-foreground) / <alpha-value>)',
        'key-neutral-border': 'rgb(var(--color-key-neutral-border) / <alpha-value>)',
        'group-orange': 'rgb(var(--color-group-orange) / <alpha-value>)',
        'group-orange-border': 'rgb(var(--color-group-orange-border) / <alpha-value>)',
        'group-blue': 'rgb(var(--color-group-blue) / <alpha-value>)',
        'group-blue-border': 'rgb(var(--color-group-blue-border) / <alpha-value>)',
        'group-purple': 'rgb(var(--color-group-purple) / <alpha-value>)',
        'group-purple-border': 'rgb(var(--color-group-purple-border) / <alpha-value>)',
        'group-cyan': 'rgb(var(--color-group-cyan) / <alpha-value>)',
        'group-cyan-border': 'rgb(var(--color-group-cyan-border) / <alpha-value>)',
        'group-green': 'rgb(var(--color-group-green) / <alpha-value>)',
        'group-green-border': 'rgb(var(--color-group-green-border) / <alpha-value>)',
        'group-neutral': 'rgb(var(--color-group-neutral) / <alpha-value>)',
        'group-neutral-border': 'rgb(var(--color-group-neutral-border) / <alpha-value>)',
      },
      animation: {
        'in': 'fadeIn 0.3s ease-in',
        'slide-in-from-right': 'slideInFromRight 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInFromRight: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
